### ISSUE TITLE
403 / Forbidden while updating calendar

### ISSUE THREAD

**Issue by agjendem** [giaever-online-iot/hacs-home-assistant-minrenovasjon#4]
Seems that the integration started failing about a week ago, I now get a 403 in the logs, and no data for the entities:

```
Denne feilen stammer fra en tilpasset integrasjon.

Logger: custom_components.minrenovasjon.calendar
Source: custom_components/minrenovasjon/calendar.py:84
Integration: MinRenovasjon (documentation)
First occurred: 15:22:21 (13 occurrences)
Last logged: 15:33:05

403, message='Forbidden', url=URL('https://komteksky.norkart.no/komtek.renovasjonwebapi/api/tommekalender?gatenavn=<removed>&gatekode=<removed>&husnr=<removed>')
Traceback (most recent call last):
  File "/config/custom_components/minrenovasjon/calendar.py", line 84, in async_update
    events = await self.__api.query(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/minrenovasjon/__init__.py", line 97, in query
    req.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1059, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://komteksky.norkart.no/komtek.renovasjonwebapi/api/tommekalender?gatenavn=<removed>&gatekode=<removed>&husnr=<removed>')
```

I suspect they've changed the appkey?

(Thanks for a nice and useful integration!)

**Comment by ArveVM** [comment]
Mine have failed to,, 
From discussion in HA-norge forum,, it seems like there have been a change and https://github.com/eyesoft/home_assistant_min_renovasjon has been reported to be fixed with new link to whatever is changed back-end?

I'm really pleased with this integration and the longer term calendar view,, so would really like it to get up and running again ;)

**Comment by agjendem** [comment]
Good catch, seems to be [this commit](https://github.com/eyesoft/home_assistant_min_renovasjon/commit/cfbec19b57cebfd1b08eeef2e50203781f75b46a) and [this issue](https://github.com/eyesoft/home_assistant_min_renovasjon/issues/23). I noticed the appkey is the same in both repositories, so it might very well just be the url.

Took a quick look, and it seems as the new proxy-solution might require a little bit of rewriting of [this repos MinRenovasjonApi](https://github.com/agjendem/hacs-home-assistant-minrenovasjon/blob/main/custom_components/minrenovasjon/__init__.py#L90) to work. The query should be sent to the base-url, and the api you actually want is [sent as a parameter "server"](https://github.com/eyesoft/home_assistant_min_renovasjon/blob/master/custom_components/min_renovasjon/config_flow.py#L231-L234).

**Comment by jmgiaever** [comment]
Hi guys,

Sorry my delayed response. Super busy with work. 

I'll try to fix it in the upcoming days. I need it myself. 

If any of you have the chance to find the new endpoints and maybe try them out, that would help a lot.
